### ISSUE TITLE
Kindly Assist

### ISSUE THREAD

**Issue by imurreflection** [tvaddonsco/plugin.video.adultflix#1]
Hi, I just found your add-on and I m extremely happy to see that it is back. However, please advise how can I change video quality to max as almost every video is being played at 480p or lower resolution but the actual site on PC has quality up to 4K. I checked the settings thoroughly but I did not find any option to change the quality. Though the message says that we can do so by changing the quality option to Auto but there is no such option in settings. Kindly extend your expertise here and thanks again for bringing this awesome add-on back.

**Comment by imurreflection** [comment]
If you do not intend to reply then why do you ask people to contact you in your add-on mate?

**Comment by tvaddonsco** [comment]
There are updates coming soon, we aren't providing one on one support at this time. Thank you for your patience.
